openapi: 3.0.3
info:
  title: Medicall API 
  version: 1.0.0
  description: |-
    Medicall es una plataforma de telemedicina diseñada para mejorar la eficiencia en las consultas médicas. Nuestro objetivo principal es permitir el acceso a servicios médicos desde cualquier ubicación, facilitando así la atención médica remota. Esta plataforma busca ofrecer una experiencia fluida y conveniente para pacientes y profesionales de la salud, contribuyendo así a optimizar el proceso de atención médica, reduciendo los tiempos de espera y los costos de desplazamiento.

    Esta api realiza: 
    - Operaciones CRUD, para el manejo de los datos de los usuarios y de los    consultas.
    - Operaciones de autenticación, para el acceso de usuarios y de la consulta.
    - Operaciones CRUD para la creacion de turnos.

    Algunos links de interés:
    - [![](https://img.shields.io/badge/Repositorio-76908e?logo=github)](https://github.com/NievasGustavo/MedicallApiExpress)
    - [![Deploy](https://vercel.com/button)](https://c17-70-m-python.vercel.app/login)
    - [![](https://img.shields.io/badge/Video%20presentacion-df4343?logo=youtube)](https://youtu.be/EA-Yu3jgn0o?si=nYKVZ3REpthCAYx9)
  
servers:
  - url: http://localhost:3000
    description: Development server

tags:
  - name: Doctors
    description: Operations about doctors
  - name: Auth
    description: Operations about authentication

paths:
  /api/doctors:
    get:
      summary: Returns a list of all the users doctors
      tags: [Doctors]
      responses:
        '200':
          description: The list of the Doctors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ViewsDocs'
        '500':
          description: Internal server error

    post:
      summary: Creates a new doctor
      tags: [Doctors]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DoctorUser'
      responses:
        '201':
          description: The doctor was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewsDocs'
        '500':
          description: Internal server error
  /api/doctors/{id}:
    get:
      summary: Returns the doctor with the specified id
      tags: [Doctors]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The doctor id
      responses:
        '200':
          description: The doctor 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewsDocs'
        '404':
          description: The doctor was not found
        '500':
          description: Internal server error
    put:
      summary: Updates the doctor with the specified id
      tags: [Doctors]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The doctor id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewsDocs'
      responses:
        '200':
          description: The doctor was updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doctors'
        '404':
          description: The doctor was not found

        '500':
          description: Internal server error

    delete:
      summary: Deletes the doctor with the specified id
      tags: [Doctors]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The doctor id
      responses:
        '204':
          description: The doctor was deleted successfully
        '404':
          description: The doctor was not found

        '500':
          description: Internal server error

  /api/auth/login:
    post:
      summary: Logs in a user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: The user was successfully logged in
          content:
            Set-Cookie:
              schema:
                type: string
                example: token=JWT_TOKEN; Path=/; HttpOnly; Secure; SameSite=None
            application/json:
              schema:
                $ref: '#/components/schemas/ViewsDocs'
        '404':
          description: The user was not found
        '500':
          description: Internal server error
  /api/auth/logout:
    post:
      summary: Logs out a user
      tags: [Auth]
      responses:
        '200':
          description: The user was successfully logged out
        '500':
          description: Internal server error

components:
    schemas:
      DoctorUser:
        type: object
        required:
          - email
        properties:
          first_name:
            type: string
          last_name:
            type: string
          dni:
            type: string
          birthdate:
            type: date
            format: date
          country_id:
            type: integer
            description: El country_id identifica el pais al que pertenece el usuario
          phone:
            type: integer
            description: El phone identifica el numero de telefono del usuario
          gender:
            type: string
          email:
            type: string
            description: El email del usuario se utiliza para la autenticación
          password:
            type: string
          rol_id:
            type: integer
            description: El rol_id identifica el rol del usuario como doctor
          specialty_id:
            type: integer
            description: El specialty_id identifica la especialidad del doctor
        example:
          first_name: John
          last_name: Doe
          dni: 12345678
          birthdate: 1990-01-01
          country_id: 1  
          phone: 123456789
          gender: Male
          email: 8b5Qm@example.com
          password: 12345
          rol_id: 2
          specialty: Cardiologia

      Doctors:
        type: object
        properties:
          id_user:
            type: string
            description: El id_user es una llave foranea de la tabla users y indica el usuario al que pertenece el doctor
          rol_id:
            type: integer
            description: El rol_id identifica el rol del usuario como doctor con una llave foranea de la tabla roles
          specialty_id:
            type: integer
            description: El specialty_id identifica la especialidad del doctor con una llave foranea de la tabla specialty
        example:
          id_user: c7aea0e0-2ff2-43e9-9b58-aa3283ea5a8b
          rol_id: 2
          specialty_id: 1
          
      ViewsDocs: 
        type: object
        properties:
          email:
            type: string
          password:
            type: string
          first_name:
            type: string
          last_name:
            type: string
          dni:
            type: integer
          birthdate:
            type: integer
          country_id:
            type: integer
          gender:
            type: string
          phone:
            type: string
          specialty_id:
            type: integer
        example:
          id: c7aea0e0-2ff2-43e9-9b58-aa3283ea5a8b
          name: {first_name: John, last_name: Doe }
          dni: 12345678
          birthdate: 1990-01-01
          phone: 123456789
          gender: Male
          rol: 2
          email: 8b5Qm@example.com
          specialty: Cardiologia
          country: Argentina

      Login:
        type: object
        properties:
          email:
            type: string
          password:
            type: string
        example:
          email: 8b5Qm@example.com
          password: 12345
