export const countries = {
	Argentina: 1,
	Bolivia: 2,
	Brazil: 3,
	Chile: 4,
	Colombia: 5,
	CostaRica: 6,
	Cuba: 7,
	DominicanRepublic: 8,
	Ecuador: 9,
	ElSalvador: 10,
	Guatemala: 11,
	Honduras: 12,
	Mexico: 13,
	Nicaragua: 14,
	Panama: 15,
	Paraguay: 16,
	Peru: 17,
	PuertoRico: 18,
	Uruguay: 19,
	Venezuela: 20,
};

export const roles = {
	Doctor: 2,
	Paciente: 1,
};

export const specialties = {
	MedicinaGeneral: 1,
	Pediatría: 2,
	Cardiología: 3,
	Dermatología: 4,
	Oftalmología: 5,
	GinecologíaYObstetricia: 6,
	CirugíaGeneral: 7,
	Psicologia: 8,
};

export const medications = {
	Analgésico: 1,
	Antipirético: 2,
	Antibiótico: 3,
	Antiinflamatorio: 4,
	Antihistamínico: 5,
	Antidepresivo: 6,
	Antiemético: 7,
	Antitusígeno: 8,
	Expectorante: 9,
	Antiemetico: 10,
	Antidiarreico: 11,
	Antifúngico: 12,
	Antiviral: 13,
	Antiséptico: 14,
	Antiespasmódico: 15,
	Vasoconstrictor: 16,
	Vasodilatador: 17,
	Broncodilatador: 18,
	DescongestionanteNasal: 19,
	Laxante: 20,
	Antiparasitario: 21,
	Antiparkinsoniano: 22,
	Antirreumático: 23,
	Diurético: 24,
	Antirretroviral: 25,
	Inmunosupresor: 26,
	Antiasmático: 27,
	Ansiolítico: 28,
	Anticonvulsivante: 29,
	Antipsicótico: 30,
	Hipnótico: 31,
	Sedante: 32,
	Estimulante: 33,
	Vitamina: 34,
};
